security context
micronaut-projects/micronaut-jaxrs pull request #149
Opened 2021-09-16 06:58 UTC by graemerocher

2021-09-16 13:57 UTC, sdelamo commented
I will check this tomorrow.

2021-09-17 04:37 UTC, sdelamo requested changes
This is a breaking change

2021-09-17 05:33 UTC, sdelamo reviewed
I've extracted and merged the security PR out of the original one: 

- [Integrate JAX-RS Security Context with Micronaut Security](https://github.com/micronaut-projects/micronaut-jaxrs/pull/152)

Moreover, I have extracted this PR [Imporve ContextAnnotationBinder](https://github.com/micronaut-projects/micronaut-jaxrs/pull/153) but I think it lacks a test. 

With [Fix Incremental compilation](https://github.com/micronaut-projects/micronaut-jaxrs/pull/156) I am not able to build locally. 

The remainder of changes in this PR, e.g. `ContextAnnotationMapper` removal and the changes to the `ContextAnnotationBinder` class signature look like a breaking change.  Not sure if those classes are consider internal but they were not annotated with `@Internal`.

2021-09-17 05:33 UTC, sdelamo commented on jaxrs-server-security/src/test/java/io/micronaut/jaxrs/security/bind/SimpleSecurityContextTest.java
> +    public Map<String, String> getProperties() {
I removed it at [Integrate JAX-RS Security Context with Micronaut Security](https://github.com/micronaut-projects/micronaut-jaxrs/pull/152). basic auth is enabled by default.

2021-09-17 05:34 UTC, sdelamo commented on jaxrs-server/src/main/java/io/micronaut/jaxrs/runtime/ext/bind/ContextAnnotationBinder.java
> +    protected ContextAnnotationBinder(
I created a new constructor, annotate it with `@Inject` and left the old one annotated with `@Deprecated` at [Integrate JAX-RS Security Context with Micronaut Security](https://github.com/micronaut-projects/micronaut-jaxrs/pull/152).

2021-09-20 08:01 UTC, graemerocher commented
these are internal classes, since they are part of the compiler plugin not the public API

2021-09-20 10:00 UTC, merged